#! /bin/sh
#  /etc/init.d/${project.artifactId}

### BEGIN INIT INFO
# Provides:          ${project.artifactId}
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Starts the daemon-test service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   ${project.deb.maintainer}
# Url:      chris.cundill.me
# Date:     19/09/2014

NAME="${project.artifactId}"
DESC="${project.description}"

# The path to Jsvc
EXEC="jsvc"

# The path to the folder containing our jar
FILE_PATH="/opt/$NAME"

# The path to the folder containing the java runtime
JAVA_HOME="/usr/lib/jvm/java-7-openjdk-armhf"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/bin/${project.build.finalName}.jar:${deb.classpath}"

# The fully qualified name of the class to execute
CLASS="${mainClass}"

# Any command line arguments to be passed to the our Java Daemon implementations init() method 
ARGS="myArg1 myArg2 myArg3"

#The user to run the daemon as
USER="${deb.user}"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="/var/log/$NAME.out"

# System.err writes to this file...
LOG_ERR="/var/err/$NAME.err"

jsvc_exec()
{   
    cd $FILE_PATH
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)  
        echo "Starting $NAME..."
        
        # Start the service
        jsvc_exec
        
        echo "$NAME has started."
    ;;
    stop)
        echo "Stopping the $NAME..."
        
        # Stop the service
        jsvc_exec "-stop"       
        
        echo "$NAME has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
            
            echo "Restarting the $NAME..."
            
            # Stop the service
            jsvc_exec "-stop"
            
            # Start the service
            jsvc_exec
            
            echo "$NAME has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac